navigation:
    menu_config:
        items:
            synolia_stock_alert_list:
                label: synolia.stockalert.entity_plural_label
                route: 'synolia_stock_alert_frontend_index'
            synolia_admin_stock_alert_list:
                route: 'synolia_stock_alert_index'
                label: synolia.stockalert.entity_plural_label
                position: 200
        tree:
            frontend_menu:
                children:
                    oro_customer_menu_customer_user_index:
                        children:
                            synolia_stock_alert_list: ~
            oro_customer_menu:
                scope_type: menu_frontend_visibility
                children:
                    synolia_stock_alert_list: ~
            oro_customer_menu_refreshing_teal:
                scope_type: menu_fronend_visibility
                children:
                    oro_customer_frontend_customer_user_profiles_and_addresses:
                        children:
                            synolia_stock_alert_list: ~
            # BO
            application_menu:
                children:
                    inventory_tab:
                        children:
                            synolia_admin_stock_alert_list: ~
